// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/mux.proto

package muxpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Frame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Frame_Hello
	//	*Frame_OpenRequest
	//	*Frame_OpenOk
	//	*Frame_OpenError
	//	*Frame_Data
	//	*Frame_Resize
	//	*Frame_Close
	//	*Frame_Ping
	//	*Frame_Pong
	Kind          isFrame_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_proto_mux_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mux_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_proto_mux_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetKind() isFrame_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Frame) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Kind.(*Frame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *Frame) GetOpenRequest() *OpenRequest {
	if x != nil {
		if x, ok := x.Kind.(*Frame_OpenRequest); ok {
			return x.OpenRequest
		}
	}
	return nil
}

func (x *Frame) GetOpenOk() *OpenOk {
	if x != nil {
		if x, ok := x.Kind.(*Frame_OpenOk); ok {
			return x.OpenOk
		}
	}
	return nil
}

func (x *Frame) GetOpenError() *OpenError {
	if x != nil {
		if x, ok := x.Kind.(*Frame_OpenError); ok {
			return x.OpenError
		}
	}
	return nil
}

func (x *Frame) GetData() *Data {
	if x != nil {
		if x, ok := x.Kind.(*Frame_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *Frame) GetResize() *Resize {
	if x != nil {
		if x, ok := x.Kind.(*Frame_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

func (x *Frame) GetClose() *Close {
	if x != nil {
		if x, ok := x.Kind.(*Frame_Close); ok {
			return x.Close
		}
	}
	return nil
}

func (x *Frame) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Kind.(*Frame_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *Frame) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Kind.(*Frame_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

type isFrame_Kind interface {
	isFrame_Kind()
}

type Frame_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"` // client -> server, first frame after connect
}

type Frame_OpenRequest struct {
	OpenRequest *OpenRequest `protobuf:"bytes,2,opt,name=open_request,json=openRequest,proto3,oneof"` // server -> client: please open a channel
}

type Frame_OpenOk struct {
	OpenOk *OpenOk `protobuf:"bytes,3,opt,name=open_ok,json=openOk,proto3,oneof"` // client -> server: channel is up
}

type Frame_OpenError struct {
	OpenError *OpenError `protobuf:"bytes,4,opt,name=open_error,json=openError,proto3,oneof"` // client -> server: could not open channel
}

type Frame_Data struct {
	Data *Data `protobuf:"bytes,5,opt,name=data,proto3,oneof"` // both: raw PTY bytes for a channel
}

type Frame_Resize struct {
	Resize *Resize `protobuf:"bytes,6,opt,name=resize,proto3,oneof"` // server -> client: new terminal size
}

type Frame_Close struct {
	Close *Close `protobuf:"bytes,7,opt,name=close,proto3,oneof"` // both: a channel ended / please end it
}

type Frame_Ping struct {
	Ping *Ping `protobuf:"bytes,8,opt,name=ping,proto3,oneof"` // both: keepalive
}

type Frame_Pong struct {
	Pong *Pong `protobuf:"bytes,9,opt,name=pong,proto3,oneof"` // both: keepalive reply
}

func (*Frame_Hello) isFrame_Kind() {}

func (*Frame_OpenRequest) isFrame_Kind() {}

func (*Frame_OpenOk) isFrame_Kind() {}

func (*Frame_OpenError) isFrame_Kind() {}

func (*Frame_Data) isFrame_Kind() {}

func (*Frame_Resize) isFrame_Kind() {}

func (*Frame_Close) isFrame_Kind() {}

func (*Frame_Ping) isFrame_Kind() {}

func (*Frame_Pong) isFrame_Kind() {}

// Sent once, immediately after the socket opens, so the operator sees who
// called home.
type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`            // runtime.GOOS
	Arch          string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`        // runtime.GOARCH
	Version       uint32                 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"` // protocol version (see PROTO_VERSION)
	Tags          string                 `protobuf:"bytes,6,opt,name=tags,proto3" json:"tags,omitempty"`        // free-form label the operator can set on the implant
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_proto_mux_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mux_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_proto_mux_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Hello) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Hello) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Hello) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *Hello) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Hello) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

// Server asks the client to spawn a new shell channel.
type OpenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     uint32                 `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"` // server-assigned, unique per host connection
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`                       // shell/command to exec; empty => default shell
	Cols          uint32                 `protobuf:"varint,3,opt,name=cols,proto3" json:"cols,omitempty"`                            // initial terminal width
	Rows          uint32                 `protobuf:"varint,4,opt,name=rows,proto3" json:"rows,omitempty"`                            // initial terminal height
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenRequest) Reset() {
	*x = OpenRequest{}
	mi := &file_proto_mux_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRequest) ProtoMessage() {}

func (x *OpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mux_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenRequest.ProtoReflect.Descriptor instead.
func (*OpenRequest) Descriptor() ([]byte, []int) {
	return file_proto_mux_proto_rawDescGZIP(), []int{2}
}

func (x *OpenRequest) GetChannelId() uint32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *OpenRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *OpenRequest) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *OpenRequest) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type OpenOk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     uint32                 `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Pid           uint32                 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"` // pid of the spawned shell (informational)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenOk) Reset() {
	*x = OpenOk{}
	mi := &file_proto_mux_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenOk) ProtoMessage() {}

func (x *OpenOk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mux_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenOk.ProtoReflect.Descriptor instead.
func (*OpenOk) Descriptor() ([]byte, []int) {
	return file_proto_mux_proto_rawDescGZIP(), []int{3}
}

func (x *OpenOk) GetChannelId() uint32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *OpenOk) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type OpenError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     uint32                 `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenError) Reset() {
	*x = OpenError{}
	mi := &file_proto_mux_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenError) ProtoMessage() {}

func (x *OpenError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mux_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenError.ProtoReflect.Descriptor instead.
func (*OpenError) Descriptor() ([]byte, []int) {
	return file_proto_mux_proto_rawDescGZIP(), []int{4}
}

func (x *OpenError) GetChannelId() uint32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *OpenError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Raw PTY bytes for one channel, in either direction.
type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     uint32                 `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_proto_mux_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mux_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_proto_mux_proto_rawDescGZIP(), []int{5}
}

func (x *Data) GetChannelId() uint32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *Data) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Server -> client: apply a new window size to the channel's PTY (SIGWINCH).
type Resize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     uint32                 `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resize) Reset() {
	*x = Resize{}
	mi := &file_proto_mux_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resize) ProtoMessage() {}

func (x *Resize) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mux_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resize.ProtoReflect.Descriptor instead.
func (*Resize) Descriptor() ([]byte, []int) {
	return file_proto_mux_proto_rawDescGZIP(), []int{6}
}

func (x *Resize) GetChannelId() uint32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *Resize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *Resize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

// Either side closing a channel. reason is best-effort/human-readable.
type Close struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     uint32                 `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"` // client -> server: shell exit code, -1 if unknown
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Close) Reset() {
	*x = Close{}
	mi := &file_proto_mux_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Close) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Close) ProtoMessage() {}

func (x *Close) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mux_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Close.ProtoReflect.Descriptor instead.
func (*Close) Descriptor() ([]byte, []int) {
	return file_proto_mux_proto_rawDescGZIP(), []int{7}
}

func (x *Close) GetChannelId() uint32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *Close) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Close) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         uint64                 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_proto_mux_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mux_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_proto_mux_proto_rawDescGZIP(), []int{8}
}

func (x *Ping) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         uint64                 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_proto_mux_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mux_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_proto_mux_proto_rawDescGZIP(), []int{9}
}

func (x *Pong) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

var File_proto_mux_proto protoreflect.FileDescriptor

const file_proto_mux_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/mux.proto\x12\x03mux\"\xf1\x02\n" +
	"\x05Frame\x12\"\n" +
	"\x05hello\x18\x01 \x01(\v2\n" +
	".mux.HelloH\x00R\x05hello\x125\n" +
	"\fopen_request\x18\x02 \x01(\v2\x10.mux.OpenRequestH\x00R\vopenRequest\x12&\n" +
	"\aopen_ok\x18\x03 \x01(\v2\v.mux.OpenOkH\x00R\x06openOk\x12/\n" +
	"\n" +
	"open_error\x18\x04 \x01(\v2\x0e.mux.OpenErrorH\x00R\topenError\x12\x1f\n" +
	"\x04data\x18\x05 \x01(\v2\t.mux.DataH\x00R\x04data\x12%\n" +
	"\x06resize\x18\x06 \x01(\v2\v.mux.ResizeH\x00R\x06resize\x12\"\n" +
	"\x05close\x18\a \x01(\v2\n" +
	".mux.CloseH\x00R\x05close\x12\x1f\n" +
	"\x04ping\x18\b \x01(\v2\t.mux.PingH\x00R\x04ping\x12\x1f\n" +
	"\x04pong\x18\t \x01(\v2\t.mux.PongH\x00R\x04pongB\x06\n" +
	"\x04kind\"\x91\x01\n" +
	"\x05Hello\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12\x18\n" +
	"\aversion\x18\x05 \x01(\rR\aversion\x12\x12\n" +
	"\x04tags\x18\x06 \x01(\tR\x04tags\"n\n" +
	"\vOpenRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\rR\tchannelId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x12\n" +
	"\x04cols\x18\x03 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x04 \x01(\rR\x04rows\"9\n" +
	"\x06OpenOk\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\rR\tchannelId\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\rR\x03pid\"D\n" +
	"\tOpenError\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\rR\tchannelId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"9\n" +
	"\x04Data\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\rR\tchannelId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"O\n" +
	"\x06Resize\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\rR\tchannelId\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\rR\x04rows\"[\n" +
	"\x05Close\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\rR\tchannelId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\"\x1c\n" +
	"\x04Ping\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x04R\x05nonce\"\x1c\n" +
	"\x04Pong\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x04R\x05nonceB;Z9github.com/nemanjan00/reverse-shell-listener/client/muxpbb\x06proto3"

var (
	file_proto_mux_proto_rawDescOnce sync.Once
	file_proto_mux_proto_rawDescData []byte
)

func file_proto_mux_proto_rawDescGZIP() []byte {
	file_proto_mux_proto_rawDescOnce.Do(func() {
		file_proto_mux_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mux_proto_rawDesc), len(file_proto_mux_proto_rawDesc)))
	})
	return file_proto_mux_proto_rawDescData
}

var file_proto_mux_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_mux_proto_goTypes = []any{
	(*Frame)(nil),       // 0: mux.Frame
	(*Hello)(nil),       // 1: mux.Hello
	(*OpenRequest)(nil), // 2: mux.OpenRequest
	(*OpenOk)(nil),      // 3: mux.OpenOk
	(*OpenError)(nil),   // 4: mux.OpenError
	(*Data)(nil),        // 5: mux.Data
	(*Resize)(nil),      // 6: mux.Resize
	(*Close)(nil),       // 7: mux.Close
	(*Ping)(nil),        // 8: mux.Ping
	(*Pong)(nil),        // 9: mux.Pong
}
var file_proto_mux_proto_depIdxs = []int32{
	1, // 0: mux.Frame.hello:type_name -> mux.Hello
	2, // 1: mux.Frame.open_request:type_name -> mux.OpenRequest
	3, // 2: mux.Frame.open_ok:type_name -> mux.OpenOk
	4, // 3: mux.Frame.open_error:type_name -> mux.OpenError
	5, // 4: mux.Frame.data:type_name -> mux.Data
	6, // 5: mux.Frame.resize:type_name -> mux.Resize
	7, // 6: mux.Frame.close:type_name -> mux.Close
	8, // 7: mux.Frame.ping:type_name -> mux.Ping
	9, // 8: mux.Frame.pong:type_name -> mux.Pong
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_proto_mux_proto_init() }
func file_proto_mux_proto_init() {
	if File_proto_mux_proto != nil {
		return
	}
	file_proto_mux_proto_msgTypes[0].OneofWrappers = []any{
		(*Frame_Hello)(nil),
		(*Frame_OpenRequest)(nil),
		(*Frame_OpenOk)(nil),
		(*Frame_OpenError)(nil),
		(*Frame_Data)(nil),
		(*Frame_Resize)(nil),
		(*Frame_Close)(nil),
		(*Frame_Ping)(nil),
		(*Frame_Pong)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mux_proto_rawDesc), len(file_proto_mux_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_mux_proto_goTypes,
		DependencyIndexes: file_proto_mux_proto_depIdxs,
		MessageInfos:      file_proto_mux_proto_msgTypes,
	}.Build()
	File_proto_mux_proto = out.File
	file_proto_mux_proto_goTypes = nil
	file_proto_mux_proto_depIdxs = nil
}
