// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/mux.proto

package muxpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Feature bits advertised by the client in Hello.features. Newer clients set
// the bits for capabilities compiled into the implant; the dashboard uses them
// to hide or disable unsupported controls when talking to older clients.
type Feature int32

const (
	Feature_FEATURE_UNSPECIFIED   Feature = 0
	Feature_FEATURE_FILE_TRANSFER Feature = 1 // FileRequest/FileStart/FileChunk/FileDone
	Feature_FEATURE_PROXY         Feature = 2 // ProxyOpen/ProxyData/ProxyClose
	Feature_FEATURE_FILE_MANAGER  Feature = 4 // FsList/FsStat
)

// Enum value maps for Feature.
var (
	Feature_name = map[int32]string{
		0: "FEATURE_UNSPECIFIED",
		1: "FEATURE_FILE_TRANSFER",
		2: "FEATURE_PROXY",
		4: "FEATURE_FILE_MANAGER",
	}
	Feature_value = map[string]int32{
		"FEATURE_UNSPECIFIED":   0,
		"FEATURE_FILE_TRANSFER": 1,
		"FEATURE_PROXY":         2,
		"FEATURE_FILE_MANAGER":  4,
	}
)

func (x Feature) Enum() *Feature {
	p := new(Feature)
	*p = x
	return p
}

func (x Feature) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Feature) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mux_proto_enumTypes[0].Descriptor()
}

func (Feature) Type() protoreflect.EnumType {
	return &file_proto_mux_proto_enumTypes[0]
}

func (x Feature) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Feature.Descriptor instead.
func (Feature) EnumDescriptor() ([]byte, []int) {
	return file_proto_mux_proto_rawDescGZIP(), []int{0}
}

type Frame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Frame_Hello
	//	*Frame_OpenRequest
	//	*Frame_OpenOk
	//	*Frame_OpenError
	//	*Frame_Data
	//	*Frame_Resize
	//	*Frame_Close
	//	*Frame_Ping
	//	*Frame_Pong
	//	*Frame_AutoExec
	//	*Frame_FileRequest
	//	*Frame_FileStart
	//	*Frame_FileChunk
	//	*Frame_FileDone
	//	*Frame_ProxyOpen
	//	*Frame_ProxyOpenOk
	//	*Frame_ProxyOpenError
	//	*Frame_ProxyData
	//	*Frame_ProxyClose
	//	*Frame_FsList
	//	*Frame_FsListResult
	//	*Frame_FsStat
	//	*Frame_FsStatResult
	Kind          isFrame_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_proto_mux_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mux_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_proto_mux_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetKind() isFrame_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Frame) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Kind.(*Frame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *Frame) GetOpenRequest() *OpenRequest {
	if x != nil {
		if x, ok := x.Kind.(*Frame_OpenRequest); ok {
			return x.OpenRequest
		}
	}
	return nil
}

func (x *Frame) GetOpenOk() *OpenOk {
	if x != nil {
		if x, ok := x.Kind.(*Frame_OpenOk); ok {
			return x.OpenOk
		}
	}
	return nil
}

func (x *Frame) GetOpenError() *OpenError {
	if x != nil {
		if x, ok := x.Kind.(*Frame_OpenError); ok {
			return x.OpenError
		}
	}
	return nil
}

func (x *Frame) GetData() *Data {
	if x != nil {
		if x, ok := x.Kind.(*Frame_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *Frame) GetResize() *Resize {
	if x != nil {
		if x, ok := x.Kind.(*Frame_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

func (x *Frame) GetClose() *Close {
	if x != nil {
		if x, ok := x.Kind.(*Frame_Close); ok {
			return x.Close
		}
	}
	return nil
}

func (x *Frame) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Kind.(*Frame_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *Frame) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Kind.(*Frame_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *Frame) GetAutoExec() *AutoExec {
	if x != nil {
		if x, ok := x.Kind.(*Frame_AutoExec); ok {
			return x.AutoExec
		}
	}
	return nil
}

func (x *Frame) GetFileRequest() *FileRequest {
	if x != nil {
		if x, ok := x.Kind.(*Frame_FileRequest); ok {
			return x.FileRequest
		}
	}
	return nil
}

func (x *Frame) GetFileStart() *FileStart {
	if x != nil {
		if x, ok := x.Kind.(*Frame_FileStart); ok {
			return x.FileStart
		}
	}
	return nil
}

func (x *Frame) GetFileChunk() *FileChunk {
	if x != nil {
		if x, ok := x.Kind.(*Frame_FileChunk); ok {
			return x.FileChunk
		}
	}
	return nil
}

func (x *Frame) GetFileDone() *FileDone {
	if x != nil {
		if x, ok := x.Kind.(*Frame_FileDone); ok {
			return x.FileDone
		}
	}
	return nil
}

func (x *Frame) GetProxyOpen() *ProxyOpen {
	if x != nil {
		if x, ok := x.Kind.(*Frame_ProxyOpen); ok {
			return x.ProxyOpen
		}
	}
	return nil
}

func (x *Frame) GetProxyOpenOk() *ProxyOpenOk {
	if x != nil {
		if x, ok := x.Kind.(*Frame_ProxyOpenOk); ok {
			return x.ProxyOpenOk
		}
	}
	return nil
}

func (x *Frame) GetProxyOpenError() *ProxyOpenError {
	if x != nil {
		if x, ok := x.Kind.(*Frame_ProxyOpenError); ok {
			return x.ProxyOpenError
		}
	}
	return nil
}

func (x *Frame) GetProxyData() *ProxyData {
	if x != nil {
		if x, ok := x.Kind.(*Frame_ProxyData); ok {
			return x.ProxyData
		}
	}
	return nil
}

func (x *Frame) GetProxyClose() *ProxyClose {
	if x != nil {
		if x, ok := x.Kind.(*Frame_ProxyClose); ok {
			return x.ProxyClose
		}
	}
	return nil
}

func (x *Frame) GetFsList() *FsList {
	if x != nil {
		if x, ok := x.Kind.(*Frame_FsList); ok {
			return x.FsList
		}
	}
	return nil
}

func (x *Frame) GetFsListResult() *FsListResult {
	if x != nil {
		if x, ok := x.Kind.(*Frame_FsListResult); ok {
			return x.FsListResult
		}
	}
	return nil
}

func (x *Frame) GetFsStat() *FsStat {
	if x != nil {
		if x, ok := x.Kind.(*Frame_FsStat); ok {
			return x.FsStat
		}
	}
	return nil
}

func (x *Frame) GetFsStatResult() *FsStatResult {
	if x != nil {
		if x, ok := x.Kind.(*Frame_FsStatResult); ok {
			return x.FsStatResult
		}
	}
	return nil
}

type isFrame_Kind interface {
	isFrame_Kind()
}

type Frame_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"` // client -> server, first frame after connect
}

type Frame_OpenRequest struct {
	OpenRequest *OpenRequest `protobuf:"bytes,2,opt,name=open_request,json=openRequest,proto3,oneof"` // server -> client: please open a channel
}

type Frame_OpenOk struct {
	OpenOk *OpenOk `protobuf:"bytes,3,opt,name=open_ok,json=openOk,proto3,oneof"` // client -> server: channel is up
}

type Frame_OpenError struct {
	OpenError *OpenError `protobuf:"bytes,4,opt,name=open_error,json=openError,proto3,oneof"` // client -> server: could not open channel
}

type Frame_Data struct {
	Data *Data `protobuf:"bytes,5,opt,name=data,proto3,oneof"` // both: raw PTY bytes for a channel
}

type Frame_Resize struct {
	Resize *Resize `protobuf:"bytes,6,opt,name=resize,proto3,oneof"` // server -> client: new terminal size
}

type Frame_Close struct {
	Close *Close `protobuf:"bytes,7,opt,name=close,proto3,oneof"` // both: a channel ended / please end it
}

type Frame_Ping struct {
	Ping *Ping `protobuf:"bytes,8,opt,name=ping,proto3,oneof"` // both: keepalive
}

type Frame_Pong struct {
	Pong *Pong `protobuf:"bytes,9,opt,name=pong,proto3,oneof"` // both: keepalive reply
}

type Frame_AutoExec struct {
	AutoExec *AutoExec `protobuf:"bytes,10,opt,name=auto_exec,json=autoExec,proto3,oneof"` // server -> client: run this script locally
}

type Frame_FileRequest struct {
	FileRequest *FileRequest `protobuf:"bytes,11,opt,name=file_request,json=fileRequest,proto3,oneof"` // downloader -> uploader: request a file
}

type Frame_FileStart struct {
	FileStart *FileStart `protobuf:"bytes,12,opt,name=file_start,json=fileStart,proto3,oneof"` // uploader  -> downloader: begin transfer
}

type Frame_FileChunk struct {
	FileChunk *FileChunk `protobuf:"bytes,13,opt,name=file_chunk,json=fileChunk,proto3,oneof"` // uploader  -> downloader: data chunk
}

type Frame_FileDone struct {
	FileDone *FileDone `protobuf:"bytes,14,opt,name=file_done,json=fileDone,proto3,oneof"` // either    -> either:    end or error
}

type Frame_ProxyOpen struct {
	ProxyOpen *ProxyOpen `protobuf:"bytes,15,opt,name=proxy_open,json=proxyOpen,proto3,oneof"` // server -> client: open a TCP tunnel
}

type Frame_ProxyOpenOk struct {
	ProxyOpenOk *ProxyOpenOk `protobuf:"bytes,18,opt,name=proxy_open_ok,json=proxyOpenOk,proto3,oneof"` // client -> server: tunnel is open
}

type Frame_ProxyOpenError struct {
	ProxyOpenError *ProxyOpenError `protobuf:"bytes,19,opt,name=proxy_open_error,json=proxyOpenError,proto3,oneof"` // client -> server: tunnel open failed
}

type Frame_ProxyData struct {
	ProxyData *ProxyData `protobuf:"bytes,16,opt,name=proxy_data,json=proxyData,proto3,oneof"` // both: raw tunnel bytes
}

type Frame_ProxyClose struct {
	ProxyClose *ProxyClose `protobuf:"bytes,17,opt,name=proxy_close,json=proxyClose,proto3,oneof"` // both: tunnel ended
}

type Frame_FsList struct {
	FsList *FsList `protobuf:"bytes,20,opt,name=fs_list,json=fsList,proto3,oneof"` // server -> client: list directory
}

type Frame_FsListResult struct {
	FsListResult *FsListResult `protobuf:"bytes,21,opt,name=fs_list_result,json=fsListResult,proto3,oneof"` // client -> server: directory listing
}

type Frame_FsStat struct {
	FsStat *FsStat `protobuf:"bytes,22,opt,name=fs_stat,json=fsStat,proto3,oneof"` // server -> client: stat path
}

type Frame_FsStatResult struct {
	FsStatResult *FsStatResult `protobuf:"bytes,23,opt,name=fs_stat_result,json=fsStatResult,proto3,oneof"` // client -> server: stat result
}

func (*Frame_Hello) isFrame_Kind() {}

func (*Frame_OpenRequest) isFrame_Kind() {}

func (*Frame_OpenOk) isFrame_Kind() {}

func (*Frame_OpenError) isFrame_Kind() {}

func (*Frame_Data) isFrame_Kind() {}

func (*Frame_Resize) isFrame_Kind() {}

func (*Frame_Close) isFrame_Kind() {}

func (*Frame_Ping) isFrame_Kind() {}

func (*Frame_Pong) isFrame_Kind() {}

func (*Frame_AutoExec) isFrame_Kind() {}

func (*Frame_FileRequest) isFrame_Kind() {}

func (*Frame_FileStart) isFrame_Kind() {}

func (*Frame_FileChunk) isFrame_Kind() {}

func (*Frame_FileDone) isFrame_Kind() {}

func (*Frame_ProxyOpen) isFrame_Kind() {}

func (*Frame_ProxyOpenOk) isFrame_Kind() {}

func (*Frame_ProxyOpenError) isFrame_Kind() {}

func (*Frame_ProxyData) isFrame_Kind() {}

func (*Frame_ProxyClose) isFrame_Kind() {}

func (*Frame_FsList) isFrame_Kind() {}

func (*Frame_FsListResult) isFrame_Kind() {}

func (*Frame_FsStat) isFrame_Kind() {}

func (*Frame_FsStatResult) isFrame_Kind() {}

// Sent once, immediately after the socket opens, so the operator sees who
// called home. The token field authenticates the client against the server's
// BUILD_TOKEN (the same token used by the /dl download endpoint); a missing
// or mismatched token causes the server to close the connection.
type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`              // runtime.GOOS
	Arch          string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`          // runtime.GOARCH
	Version       uint32                 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`   // protocol version (see PROTO_VERSION)
	Tags          string                 `protobuf:"bytes,6,opt,name=tags,proto3" json:"tags,omitempty"`          // free-form label the operator can set on the implant
	Token         string                 `protobuf:"bytes,7,opt,name=token,proto3" json:"token,omitempty"`        // BUILD_TOKEN; server rejects the connection if it mismatches
	Features      uint32                 `protobuf:"varint,8,opt,name=features,proto3" json:"features,omitempty"` // bitmap of Feature bits the client supports
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_proto_mux_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mux_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_proto_mux_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Hello) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Hello) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Hello) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *Hello) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Hello) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *Hello) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Hello) GetFeatures() uint32 {
	if x != nil {
		return x.Features
	}
	return 0
}

// Server asks the client to spawn a new shell channel.
type OpenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     uint32                 `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"` // server-assigned, unique per host connection
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`                       // shell/command to exec; empty => default shell
	Cols          uint32                 `protobuf:"varint,3,opt,name=cols,proto3" json:"cols,omitempty"`                            // initial terminal width
	Rows          uint32                 `protobuf:"varint,4,opt,name=rows,proto3" json:"rows,omitempty"`                            // initial terminal height
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenRequest) Reset() {
	*x = OpenRequest{}
	mi := &file_proto_mux_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRequest) ProtoMessage() {}

func (x *OpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mux_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenRequest.ProtoReflect.Descriptor instead.
func (*OpenRequest) Descriptor() ([]byte, []int) {
	return file_proto_mux_proto_rawDescGZIP(), []int{2}
}

func (x *OpenRequest) GetChannelId() uint32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *OpenRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *OpenRequest) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *OpenRequest) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type OpenOk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     uint32                 `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Pid           uint32                 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"` // pid of the spawned shell (informational)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenOk) Reset() {
	*x = OpenOk{}
	mi := &file_proto_mux_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenOk) ProtoMessage() {}

func (x *OpenOk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mux_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenOk.ProtoReflect.Descriptor instead.
func (*OpenOk) Descriptor() ([]byte, []int) {
	return file_proto_mux_proto_rawDescGZIP(), []int{3}
}

func (x *OpenOk) GetChannelId() uint32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *OpenOk) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type OpenError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     uint32                 `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenError) Reset() {
	*x = OpenError{}
	mi := &file_proto_mux_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenError) ProtoMessage() {}

func (x *OpenError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mux_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenError.ProtoReflect.Descriptor instead.
func (*OpenError) Descriptor() ([]byte, []int) {
	return file_proto_mux_proto_rawDescGZIP(), []int{4}
}

func (x *OpenError) GetChannelId() uint32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *OpenError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Raw PTY bytes for one channel, in either direction.
type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     uint32                 `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_proto_mux_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mux_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_proto_mux_proto_rawDescGZIP(), []int{5}
}

func (x *Data) GetChannelId() uint32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *Data) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Server -> client: apply a new window size to the channel's PTY (SIGWINCH).
type Resize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     uint32                 `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resize) Reset() {
	*x = Resize{}
	mi := &file_proto_mux_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resize) ProtoMessage() {}

func (x *Resize) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mux_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resize.ProtoReflect.Descriptor instead.
func (*Resize) Descriptor() ([]byte, []int) {
	return file_proto_mux_proto_rawDescGZIP(), []int{6}
}

func (x *Resize) GetChannelId() uint32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *Resize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *Resize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

// Either side closing a channel. reason is best-effort/human-readable.
type Close struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     uint32                 `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"` // client -> server: shell exit code, -1 if unknown
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Close) Reset() {
	*x = Close{}
	mi := &file_proto_mux_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Close) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Close) ProtoMessage() {}

func (x *Close) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mux_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Close.ProtoReflect.Descriptor instead.
func (*Close) Descriptor() ([]byte, []int) {
	return file_proto_mux_proto_rawDescGZIP(), []int{7}
}

func (x *Close) GetChannelId() uint32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *Close) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Close) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         uint64                 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_proto_mux_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mux_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_proto_mux_proto_rawDescGZIP(), []int{8}
}

func (x *Ping) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         uint64                 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_proto_mux_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mux_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_proto_mux_proto_rawDescGZIP(), []int{9}
}

func (x *Pong) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

// Server -> client: a script the client should execute locally right after
// Hello. The server picks the file based on the client's reported os: it
// reads autoexec/<os>.sh (or autoexec/<os>.ps1 for windows) from the autoexec
// directory and sends the contents here. Used for persistence / setup without
// hardcoding commands in the implant binary.
type AutoExec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            string                 `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`         // the os the server matched on (informational)
	Shell         string                 `protobuf:"bytes,2,opt,name=shell,proto3" json:"shell,omitempty"`   // "sh" or "powershell" — how to invoke the script
	Script        []byte                 `protobuf:"bytes,3,opt,name=script,proto3" json:"script,omitempty"` // the script body to execute
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoExec) Reset() {
	*x = AutoExec{}
	mi := &file_proto_mux_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoExec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoExec) ProtoMessage() {}

func (x *AutoExec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mux_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoExec.ProtoReflect.Descriptor instead.
func (*AutoExec) Descriptor() ([]byte, []int) {
	return file_proto_mux_proto_rawDescGZIP(), []int{10}
}

func (x *AutoExec) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *AutoExec) GetShell() string {
	if x != nil {
		return x.Shell
	}
	return ""
}

func (x *AutoExec) GetScript() []byte {
	if x != nil {
		return x.Script
	}
	return nil
}

// Downloader asks the uploader to send a file.
type FileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    uint32                 `protobuf:"varint,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"` // chosen by the downloader, unique per host connection
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`                                // path of the file on the uploader's side
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRequest) Reset() {
	*x = FileRequest{}
	mi := &file_proto_mux_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRequest) ProtoMessage() {}

func (x *FileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mux_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRequest.ProtoReflect.Descriptor instead.
func (*FileRequest) Descriptor() ([]byte, []int) {
	return file_proto_mux_proto_rawDescGZIP(), []int{11}
}

func (x *FileRequest) GetTransferId() uint32 {
	if x != nil {
		return x.TransferId
	}
	return 0
}

func (x *FileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// Uploader begins a file transfer in response to FileRequest (download) or as
// the first frame of an upload.
type FileStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    uint32                 `protobuf:"varint,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Size          uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"` // total bytes, 0 if unknown
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileStart) Reset() {
	*x = FileStart{}
	mi := &file_proto_mux_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileStart) ProtoMessage() {}

func (x *FileStart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mux_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileStart.ProtoReflect.Descriptor instead.
func (*FileStart) Descriptor() ([]byte, []int) {
	return file_proto_mux_proto_rawDescGZIP(), []int{12}
}

func (x *FileStart) GetTransferId() uint32 {
	if x != nil {
		return x.TransferId
	}
	return 0
}

func (x *FileStart) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileStart) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// Raw file data chunk.
type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    uint32                 `protobuf:"varint,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_proto_mux_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mux_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_proto_mux_proto_rawDescGZIP(), []int{13}
}

func (x *FileChunk) GetTransferId() uint32 {
	if x != nil {
		return x.TransferId
	}
	return 0
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Signals the end of a transfer. error is empty on success.
type FileDone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    uint32                 `protobuf:"varint,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDone) Reset() {
	*x = FileDone{}
	mi := &file_proto_mux_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDone) ProtoMessage() {}

func (x *FileDone) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mux_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDone.ProtoReflect.Descriptor instead.
func (*FileDone) Descriptor() ([]byte, []int) {
	return file_proto_mux_proto_rawDescGZIP(), []int{14}
}

func (x *FileDone) GetTransferId() uint32 {
	if x != nil {
		return x.TransferId
	}
	return 0
}

func (x *FileDone) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Server asks the client to open a TCP connection for a proxy tunnel.
type ProxyOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProxyId       uint32                 `protobuf:"varint,1,opt,name=proxy_id,json=proxyId,proto3" json:"proxy_id,omitempty"` // server-assigned, unique per host connection
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`                       // target hostname or IP
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`                      // target port
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyOpen) Reset() {
	*x = ProxyOpen{}
	mi := &file_proto_mux_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyOpen) ProtoMessage() {}

func (x *ProxyOpen) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mux_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyOpen.ProtoReflect.Descriptor instead.
func (*ProxyOpen) Descriptor() ([]byte, []int) {
	return file_proto_mux_proto_rawDescGZIP(), []int{15}
}

func (x *ProxyOpen) GetProxyId() uint32 {
	if x != nil {
		return x.ProxyId
	}
	return 0
}

func (x *ProxyOpen) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ProxyOpen) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// Client reports that the proxy tunnel was successfully opened.
type ProxyOpenOk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProxyId       uint32                 `protobuf:"varint,1,opt,name=proxy_id,json=proxyId,proto3" json:"proxy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyOpenOk) Reset() {
	*x = ProxyOpenOk{}
	mi := &file_proto_mux_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyOpenOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyOpenOk) ProtoMessage() {}

func (x *ProxyOpenOk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mux_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyOpenOk.ProtoReflect.Descriptor instead.
func (*ProxyOpenOk) Descriptor() ([]byte, []int) {
	return file_proto_mux_proto_rawDescGZIP(), []int{16}
}

func (x *ProxyOpenOk) GetProxyId() uint32 {
	if x != nil {
		return x.ProxyId
	}
	return 0
}

// Client reports that the proxy tunnel could not be opened.
type ProxyOpenError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProxyId       uint32                 `protobuf:"varint,1,opt,name=proxy_id,json=proxyId,proto3" json:"proxy_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyOpenError) Reset() {
	*x = ProxyOpenError{}
	mi := &file_proto_mux_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyOpenError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyOpenError) ProtoMessage() {}

func (x *ProxyOpenError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mux_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyOpenError.ProtoReflect.Descriptor instead.
func (*ProxyOpenError) Descriptor() ([]byte, []int) {
	return file_proto_mux_proto_rawDescGZIP(), []int{17}
}

func (x *ProxyOpenError) GetProxyId() uint32 {
	if x != nil {
		return x.ProxyId
	}
	return 0
}

func (x *ProxyOpenError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Raw bytes for one proxy tunnel, in either direction.
type ProxyData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProxyId       uint32                 `protobuf:"varint,1,opt,name=proxy_id,json=proxyId,proto3" json:"proxy_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyData) Reset() {
	*x = ProxyData{}
	mi := &file_proto_mux_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyData) ProtoMessage() {}

func (x *ProxyData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mux_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyData.ProtoReflect.Descriptor instead.
func (*ProxyData) Descriptor() ([]byte, []int) {
	return file_proto_mux_proto_rawDescGZIP(), []int{18}
}

func (x *ProxyData) GetProxyId() uint32 {
	if x != nil {
		return x.ProxyId
	}
	return 0
}

func (x *ProxyData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Either side closing a proxy tunnel. reason is best-effort/human-readable.
type ProxyClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProxyId       uint32                 `protobuf:"varint,1,opt,name=proxy_id,json=proxyId,proto3" json:"proxy_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyClose) Reset() {
	*x = ProxyClose{}
	mi := &file_proto_mux_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyClose) ProtoMessage() {}

func (x *ProxyClose) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mux_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyClose.ProtoReflect.Descriptor instead.
func (*ProxyClose) Descriptor() ([]byte, []int) {
	return file_proto_mux_proto_rawDescGZIP(), []int{19}
}

func (x *ProxyClose) GetProxyId() uint32 {
	if x != nil {
		return x.ProxyId
	}
	return 0
}

func (x *ProxyClose) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Server asks the client to list a directory's contents.
type FsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint32                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsList) Reset() {
	*x = FsList{}
	mi := &file_proto_mux_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsList) ProtoMessage() {}

func (x *FsList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mux_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsList.ProtoReflect.Descriptor instead.
func (*FsList) Descriptor() ([]byte, []int) {
	return file_proto_mux_proto_rawDescGZIP(), []int{20}
}

func (x *FsList) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *FsList) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// One entry in a directory listing.
type FsEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsDir         bool                   `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size          uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	ModTime       int64                  `protobuf:"varint,4,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"` // Unix milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsEntry) Reset() {
	*x = FsEntry{}
	mi := &file_proto_mux_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsEntry) ProtoMessage() {}

func (x *FsEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mux_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsEntry.ProtoReflect.Descriptor instead.
func (*FsEntry) Descriptor() ([]byte, []int) {
	return file_proto_mux_proto_rawDescGZIP(), []int{21}
}

func (x *FsEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FsEntry) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FsEntry) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FsEntry) GetModTime() int64 {
	if x != nil {
		return x.ModTime
	}
	return 0
}

// Client returns the result of FsList.
type FsListResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint32                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // empty on success
	Entries       []*FsEntry             `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	AbsolutePath  string                 `protobuf:"bytes,4,opt,name=absolute_path,json=absolutePath,proto3" json:"absolute_path,omitempty"` // resolved absolute path of the listed directory
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsListResult) Reset() {
	*x = FsListResult{}
	mi := &file_proto_mux_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsListResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsListResult) ProtoMessage() {}

func (x *FsListResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mux_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsListResult.ProtoReflect.Descriptor instead.
func (*FsListResult) Descriptor() ([]byte, []int) {
	return file_proto_mux_proto_rawDescGZIP(), []int{22}
}

func (x *FsListResult) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *FsListResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *FsListResult) GetEntries() []*FsEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *FsListResult) GetAbsolutePath() string {
	if x != nil {
		return x.AbsolutePath
	}
	return ""
}

// Server asks the client to stat a path.
type FsStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint32                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsStat) Reset() {
	*x = FsStat{}
	mi := &file_proto_mux_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsStat) ProtoMessage() {}

func (x *FsStat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mux_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsStat.ProtoReflect.Descriptor instead.
func (*FsStat) Descriptor() ([]byte, []int) {
	return file_proto_mux_proto_rawDescGZIP(), []int{23}
}

func (x *FsStat) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *FsStat) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// Client returns the result of FsStat.
type FsStatResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint32                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // empty on success
	Exists        bool                   `protobuf:"varint,3,opt,name=exists,proto3" json:"exists,omitempty"`
	IsDir         bool                   `protobuf:"varint,4,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size          uint64                 `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	ModTime       int64                  `protobuf:"varint,6,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"` // Unix milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsStatResult) Reset() {
	*x = FsStatResult{}
	mi := &file_proto_mux_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsStatResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsStatResult) ProtoMessage() {}

func (x *FsStatResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mux_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsStatResult.ProtoReflect.Descriptor instead.
func (*FsStatResult) Descriptor() ([]byte, []int) {
	return file_proto_mux_proto_rawDescGZIP(), []int{24}
}

func (x *FsStatResult) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *FsStatResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *FsStatResult) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *FsStatResult) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FsStatResult) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FsStatResult) GetModTime() int64 {
	if x != nil {
		return x.ModTime
	}
	return 0
}

var File_proto_mux_proto protoreflect.FileDescriptor

const file_proto_mux_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/mux.proto\x12\x03mux\"\xbb\b\n" +
	"\x05Frame\x12\"\n" +
	"\x05hello\x18\x01 \x01(\v2\n" +
	".mux.HelloH\x00R\x05hello\x125\n" +
	"\fopen_request\x18\x02 \x01(\v2\x10.mux.OpenRequestH\x00R\vopenRequest\x12&\n" +
	"\aopen_ok\x18\x03 \x01(\v2\v.mux.OpenOkH\x00R\x06openOk\x12/\n" +
	"\n" +
	"open_error\x18\x04 \x01(\v2\x0e.mux.OpenErrorH\x00R\topenError\x12\x1f\n" +
	"\x04data\x18\x05 \x01(\v2\t.mux.DataH\x00R\x04data\x12%\n" +
	"\x06resize\x18\x06 \x01(\v2\v.mux.ResizeH\x00R\x06resize\x12\"\n" +
	"\x05close\x18\a \x01(\v2\n" +
	".mux.CloseH\x00R\x05close\x12\x1f\n" +
	"\x04ping\x18\b \x01(\v2\t.mux.PingH\x00R\x04ping\x12\x1f\n" +
	"\x04pong\x18\t \x01(\v2\t.mux.PongH\x00R\x04pong\x12,\n" +
	"\tauto_exec\x18\n" +
	" \x01(\v2\r.mux.AutoExecH\x00R\bautoExec\x125\n" +
	"\ffile_request\x18\v \x01(\v2\x10.mux.FileRequestH\x00R\vfileRequest\x12/\n" +
	"\n" +
	"file_start\x18\f \x01(\v2\x0e.mux.FileStartH\x00R\tfileStart\x12/\n" +
	"\n" +
	"file_chunk\x18\r \x01(\v2\x0e.mux.FileChunkH\x00R\tfileChunk\x12,\n" +
	"\tfile_done\x18\x0e \x01(\v2\r.mux.FileDoneH\x00R\bfileDone\x12/\n" +
	"\n" +
	"proxy_open\x18\x0f \x01(\v2\x0e.mux.ProxyOpenH\x00R\tproxyOpen\x126\n" +
	"\rproxy_open_ok\x18\x12 \x01(\v2\x10.mux.ProxyOpenOkH\x00R\vproxyOpenOk\x12?\n" +
	"\x10proxy_open_error\x18\x13 \x01(\v2\x13.mux.ProxyOpenErrorH\x00R\x0eproxyOpenError\x12/\n" +
	"\n" +
	"proxy_data\x18\x10 \x01(\v2\x0e.mux.ProxyDataH\x00R\tproxyData\x122\n" +
	"\vproxy_close\x18\x11 \x01(\v2\x0f.mux.ProxyCloseH\x00R\n" +
	"proxyClose\x12&\n" +
	"\afs_list\x18\x14 \x01(\v2\v.mux.FsListH\x00R\x06fsList\x129\n" +
	"\x0efs_list_result\x18\x15 \x01(\v2\x11.mux.FsListResultH\x00R\ffsListResult\x12&\n" +
	"\afs_stat\x18\x16 \x01(\v2\v.mux.FsStatH\x00R\x06fsStat\x129\n" +
	"\x0efs_stat_result\x18\x17 \x01(\v2\x11.mux.FsStatResultH\x00R\ffsStatResultB\x06\n" +
	"\x04kind\"\xc3\x01\n" +
	"\x05Hello\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12\x18\n" +
	"\aversion\x18\x05 \x01(\rR\aversion\x12\x12\n" +
	"\x04tags\x18\x06 \x01(\tR\x04tags\x12\x14\n" +
	"\x05token\x18\a \x01(\tR\x05token\x12\x1a\n" +
	"\bfeatures\x18\b \x01(\rR\bfeatures\"n\n" +
	"\vOpenRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\rR\tchannelId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x12\n" +
	"\x04cols\x18\x03 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x04 \x01(\rR\x04rows\"9\n" +
	"\x06OpenOk\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\rR\tchannelId\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\rR\x03pid\"D\n" +
	"\tOpenError\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\rR\tchannelId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"9\n" +
	"\x04Data\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\rR\tchannelId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"O\n" +
	"\x06Resize\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\rR\tchannelId\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\rR\x04rows\"[\n" +
	"\x05Close\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\rR\tchannelId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\"\x1c\n" +
	"\x04Ping\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x04R\x05nonce\"\x1c\n" +
	"\x04Pong\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x04R\x05nonce\"H\n" +
	"\bAutoExec\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\x14\n" +
	"\x05shell\x18\x02 \x01(\tR\x05shell\x12\x16\n" +
	"\x06script\x18\x03 \x01(\fR\x06script\"B\n" +
	"\vFileRequest\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\rR\n" +
	"transferId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"T\n" +
	"\tFileStart\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\rR\n" +
	"transferId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\"@\n" +
	"\tFileChunk\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\rR\n" +
	"transferId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"A\n" +
	"\bFileDone\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\rR\n" +
	"transferId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"N\n" +
	"\tProxyOpen\x12\x19\n" +
	"\bproxy_id\x18\x01 \x01(\rR\aproxyId\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\"(\n" +
	"\vProxyOpenOk\x12\x19\n" +
	"\bproxy_id\x18\x01 \x01(\rR\aproxyId\"E\n" +
	"\x0eProxyOpenError\x12\x19\n" +
	"\bproxy_id\x18\x01 \x01(\rR\aproxyId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\":\n" +
	"\tProxyData\x12\x19\n" +
	"\bproxy_id\x18\x01 \x01(\rR\aproxyId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"?\n" +
	"\n" +
	"ProxyClose\x12\x19\n" +
	"\bproxy_id\x18\x01 \x01(\rR\aproxyId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\";\n" +
	"\x06FsList\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\rR\trequestId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"c\n" +
	"\aFsEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\x12\x19\n" +
	"\bmod_time\x18\x04 \x01(\x03R\amodTime\"\x90\x01\n" +
	"\fFsListResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\rR\trequestId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12&\n" +
	"\aentries\x18\x03 \x03(\v2\f.mux.FsEntryR\aentries\x12#\n" +
	"\rabsolute_path\x18\x04 \x01(\tR\fabsolutePath\";\n" +
	"\x06FsStat\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\rR\trequestId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\xa1\x01\n" +
	"\fFsStatResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\rR\trequestId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x16\n" +
	"\x06exists\x18\x03 \x01(\bR\x06exists\x12\x15\n" +
	"\x06is_dir\x18\x04 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x04R\x04size\x12\x19\n" +
	"\bmod_time\x18\x06 \x01(\x03R\amodTime*j\n" +
	"\aFeature\x12\x17\n" +
	"\x13FEATURE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15FEATURE_FILE_TRANSFER\x10\x01\x12\x11\n" +
	"\rFEATURE_PROXY\x10\x02\x12\x18\n" +
	"\x14FEATURE_FILE_MANAGER\x10\x04B;Z9github.com/nemanjan00/reverse-shell-listener/client/muxpbb\x06proto3"

var (
	file_proto_mux_proto_rawDescOnce sync.Once
	file_proto_mux_proto_rawDescData []byte
)

func file_proto_mux_proto_rawDescGZIP() []byte {
	file_proto_mux_proto_rawDescOnce.Do(func() {
		file_proto_mux_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mux_proto_rawDesc), len(file_proto_mux_proto_rawDesc)))
	})
	return file_proto_mux_proto_rawDescData
}

var file_proto_mux_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_mux_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_proto_mux_proto_goTypes = []any{
	(Feature)(0),           // 0: mux.Feature
	(*Frame)(nil),          // 1: mux.Frame
	(*Hello)(nil),          // 2: mux.Hello
	(*OpenRequest)(nil),    // 3: mux.OpenRequest
	(*OpenOk)(nil),         // 4: mux.OpenOk
	(*OpenError)(nil),      // 5: mux.OpenError
	(*Data)(nil),           // 6: mux.Data
	(*Resize)(nil),         // 7: mux.Resize
	(*Close)(nil),          // 8: mux.Close
	(*Ping)(nil),           // 9: mux.Ping
	(*Pong)(nil),           // 10: mux.Pong
	(*AutoExec)(nil),       // 11: mux.AutoExec
	(*FileRequest)(nil),    // 12: mux.FileRequest
	(*FileStart)(nil),      // 13: mux.FileStart
	(*FileChunk)(nil),      // 14: mux.FileChunk
	(*FileDone)(nil),       // 15: mux.FileDone
	(*ProxyOpen)(nil),      // 16: mux.ProxyOpen
	(*ProxyOpenOk)(nil),    // 17: mux.ProxyOpenOk
	(*ProxyOpenError)(nil), // 18: mux.ProxyOpenError
	(*ProxyData)(nil),      // 19: mux.ProxyData
	(*ProxyClose)(nil),     // 20: mux.ProxyClose
	(*FsList)(nil),         // 21: mux.FsList
	(*FsEntry)(nil),        // 22: mux.FsEntry
	(*FsListResult)(nil),   // 23: mux.FsListResult
	(*FsStat)(nil),         // 24: mux.FsStat
	(*FsStatResult)(nil),   // 25: mux.FsStatResult
}
var file_proto_mux_proto_depIdxs = []int32{
	2,  // 0: mux.Frame.hello:type_name -> mux.Hello
	3,  // 1: mux.Frame.open_request:type_name -> mux.OpenRequest
	4,  // 2: mux.Frame.open_ok:type_name -> mux.OpenOk
	5,  // 3: mux.Frame.open_error:type_name -> mux.OpenError
	6,  // 4: mux.Frame.data:type_name -> mux.Data
	7,  // 5: mux.Frame.resize:type_name -> mux.Resize
	8,  // 6: mux.Frame.close:type_name -> mux.Close
	9,  // 7: mux.Frame.ping:type_name -> mux.Ping
	10, // 8: mux.Frame.pong:type_name -> mux.Pong
	11, // 9: mux.Frame.auto_exec:type_name -> mux.AutoExec
	12, // 10: mux.Frame.file_request:type_name -> mux.FileRequest
	13, // 11: mux.Frame.file_start:type_name -> mux.FileStart
	14, // 12: mux.Frame.file_chunk:type_name -> mux.FileChunk
	15, // 13: mux.Frame.file_done:type_name -> mux.FileDone
	16, // 14: mux.Frame.proxy_open:type_name -> mux.ProxyOpen
	17, // 15: mux.Frame.proxy_open_ok:type_name -> mux.ProxyOpenOk
	18, // 16: mux.Frame.proxy_open_error:type_name -> mux.ProxyOpenError
	19, // 17: mux.Frame.proxy_data:type_name -> mux.ProxyData
	20, // 18: mux.Frame.proxy_close:type_name -> mux.ProxyClose
	21, // 19: mux.Frame.fs_list:type_name -> mux.FsList
	23, // 20: mux.Frame.fs_list_result:type_name -> mux.FsListResult
	24, // 21: mux.Frame.fs_stat:type_name -> mux.FsStat
	25, // 22: mux.Frame.fs_stat_result:type_name -> mux.FsStatResult
	22, // 23: mux.FsListResult.entries:type_name -> mux.FsEntry
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_proto_mux_proto_init() }
func file_proto_mux_proto_init() {
	if File_proto_mux_proto != nil {
		return
	}
	file_proto_mux_proto_msgTypes[0].OneofWrappers = []any{
		(*Frame_Hello)(nil),
		(*Frame_OpenRequest)(nil),
		(*Frame_OpenOk)(nil),
		(*Frame_OpenError)(nil),
		(*Frame_Data)(nil),
		(*Frame_Resize)(nil),
		(*Frame_Close)(nil),
		(*Frame_Ping)(nil),
		(*Frame_Pong)(nil),
		(*Frame_AutoExec)(nil),
		(*Frame_FileRequest)(nil),
		(*Frame_FileStart)(nil),
		(*Frame_FileChunk)(nil),
		(*Frame_FileDone)(nil),
		(*Frame_ProxyOpen)(nil),
		(*Frame_ProxyOpenOk)(nil),
		(*Frame_ProxyOpenError)(nil),
		(*Frame_ProxyData)(nil),
		(*Frame_ProxyClose)(nil),
		(*Frame_FsList)(nil),
		(*Frame_FsListResult)(nil),
		(*Frame_FsStat)(nil),
		(*Frame_FsStatResult)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mux_proto_rawDesc), len(file_proto_mux_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_mux_proto_goTypes,
		DependencyIndexes: file_proto_mux_proto_depIdxs,
		EnumInfos:         file_proto_mux_proto_enumTypes,
		MessageInfos:      file_proto_mux_proto_msgTypes,
	}.Build()
	File_proto_mux_proto = out.File
	file_proto_mux_proto_goTypes = nil
	file_proto_mux_proto_depIdxs = nil
}
